#!/bin/bash

alias clear='printf "\033c"'
alias vim=nvim
alias ls="ls --color -G"

cd() {
  builtin cd "${@:-$HOME}" && ls
}

osc52() {
  local input
  input=$(cat | base64 | tr -d '\n')
  printf "\e]52;c;%s\a" "$input"
}

function zle-keymap-select {
  if [[ $KEYMAP == vicmd ]]; then
    echo -ne '\e[2 q'
  else
    echo -ne '\e[6 q'
  fi
}

function zle-line-init {
  echo -ne '\e[6 q'
}

zle -N zle-keymap-select
zle -N zle-line-init
KEYTIMEOUT=1
